# Generated by Django 2.2.19 on 2022-07-24 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя Автора')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия Автора')),
                ('name_url', models.CharField(max_length=30, unique=True, verbose_name='Страница автора')),
            ],
        ),
        migrations.CreateModel(
            name='Biografy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(verbose_name='Дата смерти')),
                ('text', models.TextField(verbose_name='Имформация о жизни')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Стихи')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='posts.Author', verbose_name='Автор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL, verbose_name='Любитель поэзии')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio', to='posts.Biografy', verbose_name='Справка о писателе'),
        ),
    ]
