# Generated by Django 2.2.19 on 2022-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220725_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='biografy',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
